# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Test Day9
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  Build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Set up CMake and Ninja
      run: |
        sudo apt-get install -y cmake
        sudo apt-get install -y ninja-build

    - name: Build with Ninja
      working-directory: ${{github.workspace}}/day9
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja -S ${{github.workspace}}/day9 -B ${{github.workspace}}/day9/cmake-build-debug
        ls

    - name: Build
      # Build your program with the given configuration
      run: cmake --build day9/cmake-build-debug --target Google_Tests_run -j 6

    - name: Test
      working-directory: ${{github.workspace}}/day9
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        ls
        ls cmake-build-debug
        ls cmake-build-debug/Google-Tests
        cmake-build-debug/Google-Tests/Google_Tests_run.exe

